### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ANDREYDEN** [alisondraV/foodizzy#127]
- [x] Add Product FAB positioning
- [x] Fix icon on the dropdown
- [x] Changing user data deletes the family
- [ ] Onboarding is not shown after Google Auth from the Sign-In page
- [x] Waste doesn't delete multiple products
